import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useOrg } from "@/lib/orgContext";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Building2, CheckCircle2, ChevronRight } from "lucide-react";
import moment from "moment";
import { canAccess } from "@/lib/roles";

const PERIOD_STATUS = {
  open: { label: 'Aberta', color: 'bg-blue-50 text-blue-700' }, awaiting_client: { label: 'Aguardando cliente', color: 'bg-amber-50 text-amber-700' }, under_review: { label: 'Em revisão', color: 'bg-purple-50 text-purple-700' }, adjustment_requested: { label: 'Ajuste solicitado', color: 'bg-orange-50 text-orange-700' }, approved: { label: 'Aprovada', color: 'bg-emerald-50 text-emerald-700' }, closed: { label: 'Fechada', color: 'bg-gray-100 text-gray-500' },
};
export default function Accounting() {
  const { orgId, role } = useOrg(); const [periods,setPeriods]=useState([]),[tasks,setTasks]=useState([]),[docs,setDocs]=useState([]),[entries,setEntries]=useState([]),[receipts,setReceipts]=useState([]),[loading,setLoading]=useState(true),[tab,setTab]=useState('visao_geral'),[selectedPeriod,setSelectedPeriod]=useState(null);
  const load=async()=>{const[p,t,d,e,r]=await Promise.all([base44.entities.AccountingPeriod.filter({organization_id:orgId},"-competence",12),base44.entities.AccountingTask.filter({organization_id:orgId},"-created_date",50),base44.entities.AccountingDocument.filter({organization_id:orgId},"-created_date",50),base44.entities.FinancialEntry.filter({organization_id:orgId},"-date",100),base44.entities.FiscalReceipt.filter({organization_id:orgId},"-created_date",50)]);setPeriods(p||[]);setTasks(t||[]);setDocs(d||[]);setEntries(e||[]);setReceipts(r||[]);if(p?.length)setSelectedPeriod(p[0]);setLoading(false)}; useEffect(()=>{if(orgId)load()},[orgId]);
  const updateStatus=async(p,status)=>{await base44.entities.AccountingPeriod.update(p.id,{status,...(status==='approved'?{approved_at:new Date().toISOString()}:{}),...(status==='closed'?{reviewed_at:new Date().toISOString()}:{})});load()}; const fmt=v=>(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const pendingTasks=tasks.filter(t=>['pending','in_progress'].includes(t.status)); const month=moment().format('YYYY-MM'); const me=entries.filter(e=>(e.competence_date||e.date||'').startsWith(month)); const rev=me.filter(e=>e.type==='receita').reduce((s,e)=>s+(e.amount||e.value||0),0), exp=me.filter(e=>e.type==='despesa').reduce((s,e)=>s+(e.amount||e.value||0),0);
  if(loading)return <div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-4 border-primary/20 border-t-primary rounded-full animate-spin"/></div>;
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Contabilidade Integrada</h1><p className="text-muted-foreground text-sm mt-1">Fechamento mensal, revisão e portal do contador</p></div><Tabs value={tab} onValueChange={setTab}><TabsList className="rounded-xl flex-wrap h-auto gap-1"><TabsTrigger value="visao_geral">Visão Geral</TabsTrigger><TabsTrigger value="competencias">Competências</TabsTrigger><TabsTrigger value="tarefas">Tarefas</TabsTrigger><TabsTrigger value="despesas">Despesas em Revisão</TabsTrigger><TabsTrigger value="recibos">Recibos</TabsTrigger></TabsList></Tabs>
  {tab==='visao_geral'&&<div className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-muted-foreground">Receita do mês</p><p className="text-2xl font-bold mt-1 text-emerald-600">{fmt(rev)}</p></div><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-muted-foreground">Despesas do mês</p><p className="text-2xl font-bold mt-1 text-red-500">{fmt(exp)}</p></div><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-muted-foreground">Resultado</p><p className="text-2xl font-bold mt-1">{fmt(rev-exp)}</p></div><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-muted-foreground">Tarefas pendentes</p><p className="text-2xl font-bold mt-1">{pendingTasks.length}</p></div></div>{selectedPeriod&&<div className="bg-white rounded-2xl border p-5"><div className="flex justify-between"><div><h2 className="font-semibold">Competência atual: {selectedPeriod.competence}</h2><span className={`text-xs px-2.5 py-1 rounded-full ${PERIOD_STATUS[selectedPeriod.status]?.color}`}>{PERIOD_STATUS[selectedPeriod.status]?.label}</span></div><div>{selectedPeriod.status==='awaiting_client'&&<Button size="sm" onClick={()=>updateStatus(selectedPeriod,'under_review')}>Enviar para revisão</Button>}{canAccess(role,'accounting')&&selectedPeriod.status==='under_review'&&<Button size="sm" onClick={()=>updateStatus(selectedPeriod,'approved')}>Aprovar</Button>}{canAccess(role,'accounting')&&selectedPeriod.status==='approved'&&<Button size="sm" onClick={()=>updateStatus(selectedPeriod,'closed')}>Fechar competência</Button>}</div></div></div>}</div>}
  {tab==='competencias'&&<div className="bg-white rounded-2xl border divide-y">{periods.length===0?<div className="p-12 text-center text-muted-foreground"><Building2 className="w-10 h-10 mx-auto mb-3 opacity-30"/>Nenhuma competência encontrada</div>:periods.map(p=><div key={p.id} className="flex items-center gap-4 p-5"><div className="flex-1"><p className="font-medium">{p.competence}</p><p className="text-xs text-muted-foreground">Receita: {fmt(p.total_revenue)} · Despesa: {fmt(p.total_expense)}</p></div><span className={`text-xs px-2 py-1 rounded-full ${PERIOD_STATUS[p.status]?.color}`}>{PERIOD_STATUS[p.status]?.label}</span><ChevronRight className="w-4 h-4"/></div>)}</div>}
  {tab==='tarefas'&&<div className="bg-white rounded-2xl border divide-y">{tasks.map(t=><div key={t.id} className="flex items-center gap-4 p-5"><div className="flex-1"><p className="font-medium">{t.title}</p><p className="text-xs text-muted-foreground">{t.description}</p></div>{t.status!=='completed'&&<Button size="sm" variant="ghost" onClick={()=>base44.entities.AccountingTask.update(t.id,{status:'completed',completed_at:new Date().toISOString()}).then(load)}><CheckCircle2 className="w-4 h-4"/></Button>}</div>)}</div>}
  {tab==='despesas'&&<div className="bg-white rounded-2xl border divide-y">{entries.filter(e=>e.type==='despesa'&&e.accounting_review_status!=='approved').map(e=><div key={e.id} className="flex items-center gap-4 p-5"><div className="flex-1"><p className="font-medium">{e.description||e.category}</p></div><p className="font-semibold text-red-500">{fmt(e.amount||e.value)}</p>{canAccess(role,'accounting')&&<Button size="sm" variant="ghost" onClick={()=>base44.entities.FinancialEntry.update(e.id,{accounting_review_status:'approved'}).then(load)}>Aprovar</Button>}</div>)}</div>}
  {tab==='recibos'&&<div className="bg-white rounded-2xl border divide-y">{receipts.map(r=><div key={r.id} className="flex items-center gap-4 p-5"><div className="flex-1"><p className="font-medium">{r.beneficiary_name||r.payer_name}</p><p className="text-xs text-muted-foreground">R$ {r.amount?.toFixed(2)}</p></div><span>{r.status==='issued'?'Emitido':'Pendente'}</span></div>)}</div>}</div>;
}